Update Node.js version and add failure check for Newman
Updated Node.js version and added a step to fail the workflow if Newman tests fail.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,7 +20,7 @@ jobs:
       - name: Install Nodejs and npm
         uses: actions/setup-node@v6.5.0
         with:
-          node-version: '22'
+          node-version: '18'
 
       - name: Install Newman and Html-extra globally
         run: |
@@ -28,6 +28,7 @@ jobs:
           npm install -g newman-reporter-htmlextra
 
       - name: Run the Postman Collection with newman
+        id: newman
         continue-on-error: true
         run: |
           newman run 'Inwarranty-flow Collection.postman_collection.json' \
@@ -41,3 +42,9 @@ jobs:
         with:
           name: Newman Report
           path: newman/*.html
+
+      - name: Fail workflow if Newman tests failed
+        if: ${{ steps.newman.outcome == 'failure' }}
+        run: |
+          echo "Newman tests failed. Please check the Newman HTML report."
+          exit 1
