Update Newman test failure handling in workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,6 +28,8 @@ jobs:
           npm install -g newman-reporter-htmlextra
 
       - name: Run the Postman Collection with newman
+        id: newman
+        continue-on-error: true
         run: |
           newman run 'Inwarranty-flow Collection.postman_collection.json' \
           -e QA.postman_environment.json \
@@ -41,8 +43,8 @@ jobs:
           name: Newman Report
           path: newman/*.html
 
-      # - name: Fail workflow if Newman tests failed
-      #   if: ${{ steps.newman.outcome == 'failure' }}
-      #   run: |
-      #     echo "Newman tests failed. Please check the Newman HTML report."
-      #     exit 1
+      - name: Fail workflow if Newman tests failed
+        if: ${{ steps.newman.outcome == 'failure' }}
+        run: |
+          echo "Newman tests failed. Please check the Newman HTML report."
+          exit 1
